# Generated by Django 5.0.2 on 2024-04-23 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incentivosApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sesion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("token", models.CharField(default="", max_length=200, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="incentivosApp.usuarios",
                    ),
                ),
            ],
        ),
    ]
