# Generated by Django 5.0.2 on 2024-05-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incentivosApp", "0003_inventario_orden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventario",
            name="orden",
            field=models.CharField(max_length=30),
        ),
    ]
